/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/RubberDuck_2.2.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useChat } from '../hooks/useChat'
import { useAudio } from '../hooks/useRubberDuckSound'

export default function RubberDuck(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/RubberDuck_2.2.glb')
  const { actions, names } = useAnimations(animations, group)
  const { playRubberDuckSound } = useAudio()
  const { quackAnimation, messages } = useChat()

  useEffect(() => {
    if (messages.length === 0) return
    if (messages[messages.length - 1].sender === 'duck') {
      quackAnimation(actions, names)
      playRubberDuckSound()
    }
  }, [messages])


  return (
    <group ref={group} {...props} dispose={null}
      onClick={() => {
        quackAnimation(actions, names)
        playRubberDuckSound()
      }}>
      <group name="Scene">
        <group name="Duck" position={[0, 4.837, 0.13]} scale={1.611}>
          <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.001']} />
          <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials['Material.003']} />
          <mesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials['Material.002']} />
          <mesh name="Cube004_3" geometry={nodes.Cube004_3.geometry} material={materials['Material.005']} />
          <mesh name="Cube004_4" geometry={nodes.Cube004_4.geometry} material={materials['Material.006']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/RubberDuck_2.2.glb')
